### ISSUE TITLE
'ValueError: Unsuported CDF Type' when writing an attribute

### ISSUE THREAD

**Issue by brenard-irap** [SciQLop/CDFpp#34]
CDFpp Version: 0.7.1
Python Version: 3.9.20
System: Ubuntu 20.04

I'm not sure that this issue is really related to pycdfpp...

Using the master branch version of speasy (commit https://github.com/SciQLop/speasy/commit/a415c1a25d756b1f9cf70d475e813031175b8592), I have a bug when I save the following variable:

```python
import speasy as spz
from speasy.core.codecs import get_codec

data = spz.get_data(spz.inventories.tree.cda.SOHO.CEL.SO_K0_CEL.Heavy_ion_rate, '2002-01-01', '2002-01-10')

print(data.values)

print(data.meta)

get_codec('application/x-cdf').save_variables([data])
```

The output is:

```
[[0. 0.]
 [0. 0.]
 [0. 0.]
 ...
 [0. 0.]
 [0. 0.]
 [0. 0.]]
{'FIELDNAM': 'Heavy ion rate', 'VALIDMIN': [0.0, 0.0], 'VALIDMAX': [1000000000.0, 1000000.0], 'SCALEMIN': [0.0, 0.0], 'SCALEMAX': [1000000.0, 5.0], 'FORMAT': 'f18.5', 'VAR_TYPE': 'data', 'DICT_KEY': 'particle_flux>integral', 'FILLVAL': [-9.999999848243207e+30], 'LABL_PTR_1': ['R 0.1-50keV/e', 'R 0.02-1MeV/e'], 'UNIT_PTR': ['ions/s/cm^2', 'ions/s     '], 'DEPEND_0': 'Epoch', 'DEPEND_1': 'unit_energy', 'CATDESC': 'Heavy ion rate in 2 energy bands (0.1-50 keV/e, 0.02-1 MeV/e)', 'AVG_TYPE': ' ', 'DISPLAY_TYPE': 'time_series', 'VAR_NOTES': ' '}
Traceback (most recent call last):
  File "/home/brenard/speasy_fork/issue.py", line 10, in <module>
    get_codec('application/x-cdf').save_variables([data])
  File "/home/brenard/speasy_fork/speasy/core/codecs/bundled_codecs/istp_cdf.py", line 208, in save_variables
    _write_variable(variable, cdf, axes, compress_variables)
  File "/home/brenard/speasy_fork/speasy/core/codecs/bundled_codecs/istp_cdf.py", line 160, in _write_variable
    cdf.add_variable(
  File "/home/brenard/speasy_fork/venv/lib/python3.9/site-packages/pycdfpp/__init__.py", line 224, in _add_variable_wrapper
    var.add_attribute(name, values)
  File "/home/brenard/speasy_fork/venv/lib/python3.9/site-packages/pycdfpp/__init__.py", line 285, in _add_attribute_wrapper
    return self._add_attribute(name=name, values=v, data_type=t)
ValueError: Unsuported CDF Type
```

It seems that the bug occurs when writing the 'UNIT_PTR' attribute.

After an upgrade to version 0.7.4, I still have the issue.

**Comment by jeandet** [comment]
I suspect this is more a Speasy issue.

**Comment by brenard-irap** [comment]
It was a Speasy issue fixed by https://github.com/SciQLop/speasy/pull/166

**Comment by jeandet** [comment]
@brenard-irap  thank you :).
